apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /Users/mpiskor/PycharmProjects/chemical-products-database-webapp/infra/kubernetes/dev/pv-dir
